### ISSUE TITLE
msgtr or msgstr?

### ISSUE THREAD

**Issue by ozmuir** [mrblueblue/gettext-loader#11]
Hi, it seems there is a typo in emitted PO file, you were probably intended to use `msgstr` token instead of `msgtr`, am I wrong?

**Comment by mrblueblue** [comment]
Yes you are right! Thank you for the catch.

**Comment by sennav** [comment]
Hey, I guess this wasn't published on npm yet, the version 0.2.2 still have `msgtr` in it.
